### ISSUE TITLE
Make transit schema on mongodb atlas

### ISSUE THREAD

**Issue by itsevalieu** [itsevalieu/planetb#17]
![IMG_3275.JPG](https://images.zenhubusercontent.com/5c7f1cf29bec55391b10d52a/140bd48e-ad81-4134-8bde-73c7d7a21e1d)

**Comment by michellekli** [comment]
![image](https://user-images.githubusercontent.com/35647019/56546223-be78ce80-652e-11e9-80dc-1a6fbacad7d9.png)

final transits schema
