### ISSUE TITLE
Make exoplanet schema 

### ISSUE THREAD

**Issue by itsevalieu** [itsevalieu/planetb#18]
![exoplanets.JPG](https://images.zenhubusercontent.com/5c7f1cf29bec55391b10d52a/826d9d95-5fc6-4b8a-afc3-cbb996730ee4)

**Comment by michellekli** [comment]
![image](https://user-images.githubusercontent.com/35647019/56545961-064b2600-652e-11e9-805c-0ced65a4c93c.png)

final schema for exoplanets collection
