### ISSUE TITLE
Make React Components

### ISSUE THREAD

**Issue by sugarsyntax** [itsevalieu/planetb#9]
- [x] App
- [x] ExoplanetList
- [x] ExoplanetItem
- [x] ExoplanetTransitGraphs
- [x] OCGraph
- [x] DurationGraph
- [x] EpochGraph
- [x] TransitObservations
- [x] UserTransitObservationsList
- [x] CommunityTransitObservationsList
- [x] TransitObservationItem
- [x] Button

**Comment by itsevalieu** [comment]
Created all the initial components and routes.
